import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles, formatMoney, formatDate } from "./styles";

export interface RemittanceRow {
  idNumber: string;
  name: string;
  eeShare: string;
  erShare: string;
  ecAmount?: string;
  total: string;
}

export interface AgencyRemittanceDocumentData {
  company: { legalName: string; tin: string; employerNumber: string; employerNumberLabel: string };
  reportTitle: string;
  agencyLabel: string;
  idColumnLabel: string;
  hasEcColumn: boolean;
  period: { cutoffStart: Date; cutoffEnd: Date };
  rows: RemittanceRow[];
}

export function AgencyRemittanceDocument({ data }: { data: AgencyRemittanceDocumentData }) {
  const totals = data.rows.reduce(
    (acc, r) => ({
      ee: acc.ee + Number(r.eeShare),
      er: acc.er + Number(r.erShare),
      ec: acc.ec + Number(r.ecAmount ?? 0),
      total: acc.total + Number(r.total),
    }),
    { ee: 0, er: 0, ec: 0, total: 0 }
  );

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerBlock}>
          <Text style={styles.title}>{data.reportTitle}</Text>
          <Text style={styles.subtitle}>{data.agencyLabel}</Text>
          <Text style={styles.companyLine}>{data.company.legalName}</Text>
          <Text style={styles.companyLine}>TIN: {data.company.tin}</Text>
          <Text style={styles.companyLine}>
            {data.company.employerNumberLabel}: {data.company.employerNumber || "—"}
          </Text>
          <Text style={styles.companyLine}>
            Applicable period: {formatDate(data.period.cutoffStart)} - {formatDate(data.period.cutoffEnd)}
          </Text>
        </View>

        <View style={styles.table}>
          <View style={styles.headerRow}>
            <Text style={styles.cellHeader}>{data.idColumnLabel}</Text>
            <Text style={[styles.cellHeader, { flex: 2 }]}>Employee Name</Text>
            <Text style={styles.cellHeader}>EE Share</Text>
            <Text style={styles.cellHeader}>ER Share</Text>
            {data.hasEcColumn && <Text style={styles.cellHeader}>EC</Text>}
            <Text style={styles.cellHeader}>Total</Text>
          </View>
          {data.rows.map((r, i) => (
            <View style={styles.row} key={i}>
              <Text style={styles.cell}>{r.idNumber || "—"}</Text>
              <Text style={[styles.cell, { flex: 2 }]}>{r.name}</Text>
              <Text style={styles.cellRight}>{formatMoney(r.eeShare)}</Text>
              <Text style={styles.cellRight}>{formatMoney(r.erShare)}</Text>
              {data.hasEcColumn && <Text style={styles.cellRight}>{formatMoney(r.ecAmount ?? 0)}</Text>}
              <Text style={styles.cellRight}>{formatMoney(r.total)}</Text>
            </View>
          ))}
          <View style={styles.totalsRow}>
            <Text style={styles.cell}>TOTAL</Text>
            <Text style={[styles.cell, { flex: 2 }]}></Text>
            <Text style={styles.cellRight}>{formatMoney(totals.ee)}</Text>
            <Text style={styles.cellRight}>{formatMoney(totals.er)}</Text>
            {data.hasEcColumn && <Text style={styles.cellRight}>{formatMoney(totals.ec)}</Text>}
            <Text style={styles.cellRight}>{formatMoney(totals.total)}</Text>
          </View>
        </View>

        <Text style={styles.footer}>
          Generated by PH Payroll from a posted, immutable payroll run. Verify field layout against the
          official {data.agencyLabel} template before submission.
        </Text>
      </Page>
    </Document>
  );
}
