import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles, formatDate } from "./styles";

export interface CertificateOfEmploymentDocumentData {
  company: { legalName: string; registeredAddress: string };
  employee: {
    fullName: string;
    positionTitle: string;
    dateHired: Date;
    dateSeparated: Date | null;
  };
  issuedDate: Date;
}

// No monetary figures — DOLE Labor Advisory 06-20 requires this within 3
// days of an employee's request, separately from final pay's dollar math.
export function CertificateOfEmploymentDocument({ data }: { data: CertificateOfEmploymentDocumentData }) {
  const employmentSpan = data.employee.dateSeparated
    ? `${formatDate(data.employee.dateHired)} to ${formatDate(data.employee.dateSeparated)}`
    : `${formatDate(data.employee.dateHired)} to present`;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerBlock}>
          <Text style={styles.title}>{data.company.legalName}</Text>
          <Text style={styles.companyLine}>{data.company.registeredAddress}</Text>
          <Text style={styles.subtitle}>Certificate of Employment</Text>
        </View>

        <Text style={{ marginTop: 20, marginBottom: 20, lineHeight: 1.6 }}>
          This is to certify that {data.employee.fullName} was employed by {data.company.legalName} as{" "}
          {data.employee.positionTitle} from {employmentSpan}.
        </Text>

        <Text style={{ marginBottom: 20, lineHeight: 1.6 }}>
          This certification is issued upon the employee&apos;s request for whatever legal purpose it may serve.
        </Text>

        <Text style={{ marginTop: 30 }}>Issued on {formatDate(data.issuedDate)}.</Text>

        <Text style={styles.footer}>Generated by PH Payroll.</Text>
      </Page>
    </Document>
  );
}
