import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles, formatMoney, formatDate } from "./styles";

export interface FinalPayStatementDocumentData {
  company: { legalName: string; tin: string; registeredAddress: string };
  employee: { employeeNumber: string; fullName: string; positionTitle: string };
  finalPayNumber: number;
  separationDate: Date;
  separationCategory: string;
  lineItems: { category: string; description: string; direction: string; amount: string; isTaxExempt: boolean }[];
  grossFinalPay: string;
  totalDeductions: string;
  netFinalPay: string;
}

export function FinalPayStatementDocument({ data }: { data: FinalPayStatementDocumentData }) {
  const earnings = data.lineItems.filter((li) => li.direction === "EARNING");
  const deductions = data.lineItems.filter((li) => li.direction === "DEDUCTION");
  const isNegative = Number(data.netFinalPay) < 0;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerBlock}>
          <Text style={styles.title}>{data.company.legalName}</Text>
          <Text style={styles.companyLine}>TIN: {data.company.tin}</Text>
          <Text style={styles.companyLine}>{data.company.registeredAddress}</Text>
          <Text style={styles.subtitle}>
            Final Pay Statement #{data.finalPayNumber} · Separation date {formatDate(data.separationDate)} ·{" "}
            {data.separationCategory.replaceAll("_", " ")}
          </Text>
        </View>

        <View style={styles.kvRow}>
          <Text style={styles.kvLabel}>Employee</Text>
          <Text style={styles.kvValue}>
            {data.employee.fullName} ({data.employee.employeeNumber})
          </Text>
        </View>
        <View style={styles.kvRow}>
          <Text style={styles.kvLabel}>Position</Text>
          <Text style={styles.kvValue}>{data.employee.positionTitle}</Text>
        </View>

        <Text style={styles.sectionTitle}>Earnings</Text>
        <View style={styles.table}>
          <View style={styles.headerRow}>
            <Text style={styles.cellHeader}>Description</Text>
            <Text style={styles.cellHeader}>Tax status</Text>
            <Text style={styles.cellHeader}>Amount</Text>
          </View>
          {earnings.map((li, i) => (
            <View style={styles.row} key={i}>
              <Text style={styles.cell}>{li.description}</Text>
              <Text style={styles.cell}>{li.isTaxExempt ? "Exempt" : "Taxable"}</Text>
              <Text style={styles.cellRight}>{formatMoney(li.amount)}</Text>
            </View>
          ))}
          <View style={styles.totalsRow}>
            <Text style={styles.cell}>Gross Final Pay</Text>
            <Text style={styles.cell}></Text>
            <Text style={styles.cellRight}>{formatMoney(data.grossFinalPay)}</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Deductions</Text>
        <View style={styles.table}>
          {deductions.length === 0 ? (
            <View style={styles.row}>
              <Text style={styles.cell}>None</Text>
            </View>
          ) : (
            deductions.map((li, i) => (
              <View style={styles.row} key={i}>
                <Text style={styles.cell}>{li.description}</Text>
                <Text style={styles.cellRight}>({formatMoney(li.amount)})</Text>
              </View>
            ))
          )}
          <View style={styles.totalsRow}>
            <Text style={styles.cell}>Total Deductions</Text>
            <Text style={styles.cellRight}>({formatMoney(data.totalDeductions)})</Text>
          </View>
        </View>

        <View style={[styles.totalsRow, { marginTop: 10, borderTop: "1pt solid #111827" }]}>
          <Text style={styles.cell}>{isNegative ? "AMOUNT OWED TO COMPANY" : "NET FINAL PAY"}</Text>
          <Text style={styles.cellRight}>{formatMoney(Math.abs(Number(data.netFinalPay)))}</Text>
        </View>

        <Text style={styles.footer}>
          Generated by PH Payroll. This statement reflects a posted, immutable final pay run, per DOLE Labor
          Advisory No. 06-20.
        </Text>
      </Page>
    </Document>
  );
}
