import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles, formatMoney, formatDate } from "./styles";

export interface Form2307DocumentData {
  company: { legalName: string; tin: string; registeredAddress: string };
  contractor: { name: string; tin: string; address: string; atcCode: string };
  payment: {
    paymentNumber: number;
    paymentDate: Date;
    grossAmount: string;
    ewtRate: string;
    ewtAmount: string;
    netAmount: string;
    invoiceReference: string | null;
  };
}

export function Form2307Document({ data }: { data: Form2307DocumentData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerBlock}>
          <Text style={styles.title}>BIR Form 2307</Text>
          <Text style={styles.subtitle}>Certificate of Creditable Tax Withheld at Source</Text>
        </View>

        <Text style={styles.sectionTitle}>Payor (Withholding Agent)</Text>
        <View style={styles.kvRow}>
          <Text style={styles.kvLabel}>Name</Text>
          <Text style={styles.kvValue}>{data.company.legalName}</Text>
        </View>
        <View style={styles.kvRow}>
          <Text style={styles.kvLabel}>TIN</Text>
          <Text style={styles.kvValue}>{data.company.tin}</Text>
        </View>
        <View style={styles.kvRow}>
          <Text style={styles.kvLabel}>Address</Text>
          <Text style={styles.kvValue}>{data.company.registeredAddress}</Text>
        </View>

        <Text style={styles.sectionTitle}>Payee</Text>
        <View style={styles.kvRow}>
          <Text style={styles.kvLabel}>Name</Text>
          <Text style={styles.kvValue}>{data.contractor.name}</Text>
        </View>
        <View style={styles.kvRow}>
          <Text style={styles.kvLabel}>TIN</Text>
          <Text style={styles.kvValue}>{data.contractor.tin}</Text>
        </View>
        <View style={styles.kvRow}>
          <Text style={styles.kvLabel}>Address</Text>
          <Text style={styles.kvValue}>{data.contractor.address}</Text>
        </View>
        <View style={styles.kvRow}>
          <Text style={styles.kvLabel}>ATC</Text>
          <Text style={styles.kvValue}>{data.contractor.atcCode}</Text>
        </View>

        <Text style={styles.sectionTitle}>Payment Details</Text>
        <View style={styles.table}>
          <View style={styles.row}>
            <Text style={styles.cell}>Payment #</Text>
            <Text style={styles.cellRight}>{data.payment.paymentNumber}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.cell}>Payment Date</Text>
            <Text style={styles.cellRight}>{formatDate(data.payment.paymentDate)}</Text>
          </View>
          {data.payment.invoiceReference && (
            <View style={styles.row}>
              <Text style={styles.cell}>Invoice/Reference #</Text>
              <Text style={styles.cellRight}>{data.payment.invoiceReference}</Text>
            </View>
          )}
          <View style={styles.row}>
            <Text style={styles.cell}>Gross Income Payment</Text>
            <Text style={styles.cellRight}>{formatMoney(data.payment.grossAmount)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.cell}>Tax Rate</Text>
            <Text style={styles.cellRight}>{(Number(data.payment.ewtRate) * 100).toFixed(2)}%</Text>
          </View>
          <View style={styles.totalsRow}>
            <Text style={styles.cell}>Tax Withheld</Text>
            <Text style={styles.cellRight}>{formatMoney(data.payment.ewtAmount)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.cell}>Net Amount Paid</Text>
            <Text style={styles.cellRight}>{formatMoney(data.payment.netAmount)}</Text>
          </View>
        </View>

        <Text style={styles.footer}>
          Generated by PH Payroll from a posted, immutable contractor payment record. Verify field layout
          against the official BIR 2307 template before issuance.
        </Text>
      </Page>
    </Document>
  );
}
