import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles, formatMoney, formatDate } from "./styles";

export interface Form1601CCutoffRow {
  periodType: string;
  cutoffStart: Date;
  cutoffEnd: Date;
  employeeCount: number;
  totalCompensation: string;
  totalTaxWithheld: string;
}

export interface Form1601CDocumentData {
  company: { legalName: string; tin: string; rdoCode: string };
  month: number;
  year: number;
  cutoffs: Form1601CCutoffRow[];
  totalTaxWithheld: string;
}

const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

export function Form1601CDocument({ data }: { data: Form1601CDocumentData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerBlock}>
          <Text style={styles.title}>BIR Form 1601-C</Text>
          <Text style={styles.subtitle}>
            Monthly Remittance Return of Income Taxes Withheld on Compensation
          </Text>
          <Text style={styles.companyLine}>{data.company.legalName}</Text>
          <Text style={styles.companyLine}>TIN: {data.company.tin}</Text>
          <Text style={styles.companyLine}>RDO Code: {data.company.rdoCode}</Text>
          <Text style={styles.companyLine}>
            For the month of {MONTH_NAMES[data.month - 1]} {data.year}
          </Text>
        </View>

        <Text style={styles.sectionTitle}>Cutoff Breakdown</Text>
        <View style={styles.table}>
          <View style={styles.headerRow}>
            <Text style={styles.cellHeader}>Cutoff</Text>
            <Text style={styles.cellHeader}>Employees</Text>
            <Text style={styles.cellHeader}>Total Compensation</Text>
            <Text style={styles.cellHeader}>Tax Withheld</Text>
          </View>
          {data.cutoffs.map((c, i) => (
            <View style={styles.row} key={i}>
              <Text style={styles.cell}>
                {formatDate(c.cutoffStart)} - {formatDate(c.cutoffEnd)}
              </Text>
              <Text style={styles.cellRight}>{c.employeeCount}</Text>
              <Text style={styles.cellRight}>{formatMoney(c.totalCompensation)}</Text>
              <Text style={styles.cellRight}>{formatMoney(c.totalTaxWithheld)}</Text>
            </View>
          ))}
        </View>

        <View style={[styles.totalsRow, { marginTop: 10, borderTop: "1pt solid #111827" }]}>
          <Text style={styles.cell}>TOTAL TAX WITHHELD FOR THE MONTH</Text>
          <Text style={styles.cellRight}>{formatMoney(data.totalTaxWithheld)}</Text>
        </View>

        {data.cutoffs.length < 2 && (
          <Text style={[styles.footer, { color: "#b91c1c" }]}>
            Warning: fewer than 2 posted cutoffs found for this month. A complete 1601-C requires both the
            1st-15th and 16th-end payroll runs to be posted.
          </Text>
        )}

        <Text style={styles.footer}>
          Generated by PH Payroll from posted, immutable payroll runs. Verify field layout against the
          official BIR 1601-C template before filing.
        </Text>
      </Page>
    </Document>
  );
}
