import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles, formatMoney, formatDate } from "./styles";

export interface PayrollRegisterRow {
  employeeNumber: string;
  fullName: string;
  grossPay: string;
  totalStatutoryDeductions: string;
  totalOtherDeductions: string;
  netPay: string;
}

export interface PayrollRegisterDocumentData {
  company: { legalName: string; tin: string };
  period: { cutoffStart: Date; cutoffEnd: Date; payDate: Date };
  runNumber: number;
  rows: PayrollRegisterRow[];
}

export function PayrollRegisterDocument({ data }: { data: PayrollRegisterDocumentData }) {
  const totals = data.rows.reduce(
    (acc, r) => ({
      gross: acc.gross + Number(r.grossPay),
      statutory: acc.statutory + Number(r.totalStatutoryDeductions),
      other: acc.other + Number(r.totalOtherDeductions),
      net: acc.net + Number(r.netPay),
    }),
    { gross: 0, statutory: 0, other: 0, net: 0 }
  );

  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <View style={styles.headerBlock}>
          <Text style={styles.title}>{data.company.legalName}</Text>
          <Text style={styles.companyLine}>TIN: {data.company.tin}</Text>
          <Text style={styles.subtitle}>
            Payroll Register · Run #{data.runNumber} · {formatDate(data.period.cutoffStart)} -{" "}
            {formatDate(data.period.cutoffEnd)} · Pay date {formatDate(data.period.payDate)}
          </Text>
        </View>

        <View style={styles.table}>
          <View style={styles.headerRow}>
            <Text style={styles.cellHeader}>Employee #</Text>
            <Text style={[styles.cellHeader, { flex: 2 }]}>Name</Text>
            <Text style={styles.cellHeader}>Gross Pay</Text>
            <Text style={styles.cellHeader}>Statutory Ded.</Text>
            <Text style={styles.cellHeader}>Other Ded.</Text>
            <Text style={styles.cellHeader}>Net Pay</Text>
          </View>
          {data.rows.map((r, i) => (
            <View style={styles.row} key={i}>
              <Text style={styles.cell}>{r.employeeNumber}</Text>
              <Text style={[styles.cell, { flex: 2 }]}>{r.fullName}</Text>
              <Text style={styles.cellRight}>{formatMoney(r.grossPay)}</Text>
              <Text style={styles.cellRight}>{formatMoney(r.totalStatutoryDeductions)}</Text>
              <Text style={styles.cellRight}>{formatMoney(r.totalOtherDeductions)}</Text>
              <Text style={styles.cellRight}>{formatMoney(r.netPay)}</Text>
            </View>
          ))}
          <View style={styles.totalsRow}>
            <Text style={styles.cell}>TOTAL</Text>
            <Text style={[styles.cell, { flex: 2 }]}></Text>
            <Text style={styles.cellRight}>{formatMoney(totals.gross)}</Text>
            <Text style={styles.cellRight}>{formatMoney(totals.statutory)}</Text>
            <Text style={styles.cellRight}>{formatMoney(totals.other)}</Text>
            <Text style={styles.cellRight}>{formatMoney(totals.net)}</Text>
          </View>
        </View>

        <Text style={styles.footer}>Generated by PH Payroll from a posted, immutable payroll run.</Text>
      </Page>
    </Document>
  );
}
