import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles, formatMoney, formatDate } from "./styles";

export interface PayslipDocumentData {
  company: { legalName: string; tin: string; registeredAddress: string };
  employee: { employeeNumber: string; fullName: string; positionTitle: string };
  period: { cutoffStart: Date; cutoffEnd: Date; payDate: Date };
  lineItems: { category: string; direction: string; description: string; amount: string }[];
  grossPay: string;
  totalStatutoryDeductions: string;
  totalOtherDeductions: string;
  netPay: string;
}

export function PayslipDocument({ data }: { data: PayslipDocumentData }) {
  const earnings = data.lineItems.filter((li) => li.direction === "EARNING");
  const deductions = data.lineItems.filter((li) => li.direction === "DEDUCTION");
  const employerContributions = data.lineItems.filter((li) => li.direction === "EMPLOYER_CONTRIBUTION");

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerBlock}>
          <Text style={styles.title}>{data.company.legalName}</Text>
          <Text style={styles.companyLine}>TIN: {data.company.tin}</Text>
          <Text style={styles.companyLine}>{data.company.registeredAddress}</Text>
          <Text style={styles.subtitle}>
            Payslip · {formatDate(data.period.cutoffStart)} - {formatDate(data.period.cutoffEnd)} · Pay date{" "}
            {formatDate(data.period.payDate)}
          </Text>
        </View>

        <View style={styles.kvRow}>
          <Text style={styles.kvLabel}>Employee</Text>
          <Text style={styles.kvValue}>
            {data.employee.fullName} ({data.employee.employeeNumber})
          </Text>
        </View>
        <View style={styles.kvRow}>
          <Text style={styles.kvLabel}>Position</Text>
          <Text style={styles.kvValue}>{data.employee.positionTitle}</Text>
        </View>

        <Text style={styles.sectionTitle}>Earnings</Text>
        <View style={styles.table}>
          {earnings.map((li, i) => (
            <View style={styles.row} key={i}>
              <Text style={styles.cell}>{li.description}</Text>
              <Text style={styles.cellRight}>{formatMoney(li.amount)}</Text>
            </View>
          ))}
          <View style={styles.totalsRow}>
            <Text style={styles.cell}>Gross Pay</Text>
            <Text style={styles.cellRight}>{formatMoney(data.grossPay)}</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Deductions</Text>
        <View style={styles.table}>
          {deductions.length === 0 ? (
            <View style={styles.row}>
              <Text style={styles.cell}>None</Text>
            </View>
          ) : (
            deductions.map((li, i) => (
              <View style={styles.row} key={i}>
                <Text style={styles.cell}>{li.description}</Text>
                <Text style={styles.cellRight}>({formatMoney(li.amount)})</Text>
              </View>
            ))
          )}
          <View style={styles.totalsRow}>
            <Text style={styles.cell}>Total Deductions</Text>
            <Text style={styles.cellRight}>
              ({formatMoney(Number(data.totalStatutoryDeductions) + Number(data.totalOtherDeductions))})
            </Text>
          </View>
        </View>

        <View style={[styles.totalsRow, { marginTop: 10, borderTop: "1pt solid #111827" }]}>
          <Text style={styles.cell}>NET PAY</Text>
          <Text style={styles.cellRight}>{formatMoney(data.netPay)}</Text>
        </View>

        {employerContributions.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Employer Contributions (not deducted from pay)</Text>
            <View style={styles.table}>
              {employerContributions.map((li, i) => (
                <View style={styles.row} key={i}>
                  <Text style={styles.cell}>{li.description}</Text>
                  <Text style={styles.cellRight}>{formatMoney(li.amount)}</Text>
                </View>
              ))}
            </View>
          </>
        )}

        <Text style={styles.footer}>
          Generated by PH Payroll. This payslip reflects a posted, immutable payroll run.
        </Text>
      </Page>
    </Document>
  );
}
